#########################################################
# This file has been automatically generated by gem2tgz #
#########################################################
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "httpclient"
  s.version = "2.8.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Hiroshi Nakamura"]
  s.date = "2016-12-09"
  s.email = "nahi@ruby-lang.org"
  s.executables = ["httpclient"]
  s.files = ["README.md", "bin/httpclient", "bin/jsonclient", "lib/hexdump.rb", "lib/http-access2.rb", "lib/http-access2/cookie.rb", "lib/http-access2/http.rb", "lib/httpclient.rb", "lib/httpclient/auth.rb", "lib/httpclient/cacert.pem", "lib/httpclient/cacert1024.pem", "lib/httpclient/connection.rb", "lib/httpclient/cookie.rb", "lib/httpclient/http.rb", "lib/httpclient/include_client.rb", "lib/httpclient/jruby_ssl_socket.rb", "lib/httpclient/session.rb", "lib/httpclient/ssl_config.rb", "lib/httpclient/ssl_socket.rb", "lib/httpclient/timeout.rb", "lib/httpclient/util.rb", "lib/httpclient/version.rb", "lib/httpclient/webagent-cookie.rb", "lib/jsonclient.rb", "lib/oauthclient.rb", "sample/async.rb", "sample/auth.rb", "sample/cookie.rb", "sample/dav.rb", "sample/howto.rb", "sample/jsonclient.rb", "sample/oauth_buzz.rb", "sample/oauth_friendfeed.rb", "sample/oauth_twitter.rb", "sample/ssl/0cert.pem", "sample/ssl/0key.pem", "sample/ssl/1000cert.pem", "sample/ssl/1000key.pem", "sample/ssl/htdocs/index.html", "sample/ssl/ssl_client.rb", "sample/ssl/webrick_httpsd.rb", "sample/stream.rb", "sample/thread.rb", "sample/wcat.rb", "test/ca-chain.pem", "test/ca.cert", "test/client-pass.key", "test/client.cert", "test/client.key", "test/helper.rb", "test/htdigest", "test/htpasswd", "test/jruby_ssl_socket/test_pemutils.rb", "test/runner.rb", "test/server.cert", "test/server.key", "test/sslsvr.rb", "test/subca.cert", "test/test_auth.rb", "test/test_cookie.rb", "test/test_hexdump.rb", "test/test_http-access2.rb", "test/test_httpclient.rb", "test/test_include_client.rb", "test/test_jsonclient.rb", "test/test_ssl.rb", "test/test_webagent-cookie.rb"]
  s.homepage = "https://github.com/nahi/httpclient"
  s.licenses = ["ruby"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.23"
  s.summary = "gives something like the functionality of libwww-perl (LWP) in Ruby"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end
