.\"                                      Hey, EMACS: -*- nroff -*-
.TH httpclient 1 "2013-06-10"
.SH NAME
httpclient \- Shell command for performing HTTP requests using Ruby httpclient
.SH SYNOPSIS
.TP
httpclient <method> <uri> [params]
.TP
httpclient
.SH DESCRIPTION
This program is an example/companion to the Ruby httpclient module,
but can be used as a complete standalone HTTP client.
.PP
If invoked with a method and an URI, the specified URI will be
requested via the method given from its server. The allowed methods
are \fBhead\fP, \fBget\fP, \fBpost\fP, \fBput\fP, \fBdelete\fP,
\fBoptions\fP, \fBpropfind\fP, \fBproppatch\fP and
\fBtrace\fP.
.PP
Parameters can be specified as a third parameter and will be delivered
accordingly (i.e. appended to the URI after a \fB?\fP sign if the
method is \fBget\fP, but as the posted body if the method is
\fBpost\fP)
.PP
Please note that no checks are done as to whether the requested
parameters make sense in the context they are specified, they are just
sent as-is.
.TP
$ httpclient get https://www.google.co.jp/ q=ruby
.PP
Starting from version 2.6.0 httpclient supports command \fBdownload\fP.
.TP
$ httpclient download http://host/path > file
.PP
If no parameters are specified, an interactive Ruby (\fBirb\fP)
session will be opened, binding an HTTPClient object as 'self'. You
can then call HTTPClient instance methods like:
.TP
$ httpclient
>> get "https://www.google.co.jp/", :q => :ruby
.PP
Httpclient will print the `wiredump' of your request (that is, the
commands sent to the server via HTTP), then the request's headers, and
finally the result.
.SH OPTIONS
.SH AUTHOR
Gunnar Wolf <gwolf@debian.org>
.SH NOTES
This manual page was written by Gunnar Wolf <gwolf@debian.org>
for the Debian project, but can be freely used by others.

This is free documentation; you can redistribute it and/or modify it
under the terms of the GNU General Public License as published by the
Free Software Foundation; either version 2 of the License, or (at your
option) any later version.
